let d = document.body.firstElementChild
console.log(d)
console.log(typeof(document))
console.log(typeof(window))
console.log(d.rows)
console.log(d.caption)
console.log(d.tHead)
console.log(d.tHead)
console.log(d.Bodies)
console.log(d.tHead.firstElementChild)