import turtle
x1, y1 = input("Enter the x and y coordinates for first points : ").split()
x1 = int(x1)
y1 = int(y1)
x2, y2 = input("Enter the x and y coordinates for sedond points : ").split()
x2 = int(x2)
y2 = int(y2)
dist = ((((x1 - x2)**2) + ((y1 - y2)**2))**(0.5))
pt1 = (x1, y1)
pt2 = (x2, y2)
mdpt = (((x1 + x2)/2), ((y1 + y2)/2))
t = turtle.Turtle()
s = turtle.Screen()
s.bgcolor("purple")
s.title("Line and Mid-Point")
t.speed(5)
t.shape("turtle")

t.penup()
t.goto(pt1)
t.pensize(5)
t.pendown()
t.goto(pt2)

t.penup()
t.color("yellow", "yellow")
t.goto(pt1)
t.pensize(15)
t.pendown()
t.circle(1)

t.penup()
t.color("yellow", "yellow")
t.goto(pt2)
t.pensize(15)
t.pendown()
t.circle(1)

t.penup()
t.color("yellow", "yellow")
t.goto(mdpt)
t.pensize(15)
t.pendown()
t.circle(1)

t.hideturtle()

turtle.done()