#####TURTLE (VISITIING CARD):
import turtle
t = turtle.Turtle()
t.speed(0) # 1:slowest, 3:slow, 5:normal, 10:fast, 0:fastest
card=turtle.Screen()
t.penup()
t.goto(-220,210)
t.pendown()
def rectangle(x,y):
  t.fd(x)
  t.rt(90)
  t.fd(y)
  t.rt(90)
  t.fd(x)
  t.rt(90)
  t.fd(y)
  t.rt(90)
rectangle(450,300)
t.penup()
t.goto(-200,200)
t.pendown()
rectangle(100,80)
t.penup()
t.goto(-160,120)
t.pendown()
t.fillcolor("black")
t.begin_fill()
rectangle(20,8)
t.end_fill()
t.penup()
t.goto(-170,112)
t.pendown()
t.fillcolor("black")
t.begin_fill()
rectangle(40,5)
t.end_fill()
t.penup()
t.goto(-170,170)
t.pendown()
t.write("computer")
t.fillcolor("blue")
t.penup()
t.goto(-220,0)
t.begin_fill()
t.pendown()
t.rt(90)
t.fd(90)
t.left(90)
t.fd(450)
t.lt(90)
t.fd(140)
t.lt(70)
t.circle(200,50)
t.circle(-207,90)
t.end_fill()
t.penup()
t.goto(-170,85)
t.pendown()
t.write("COMPUTER",font=("verdana",8))
t.penup()
t.goto(-166,70)
t.pendown()
t.write("SYSTEM",font=("verdana",8))
t.penup()
t.goto(-50,120)
t.pendown()
t.write("Visiting Card",font=("verdana",30))
t.hideturtle()

turtle.done()